# Generated by Django 4.2.7 on 2024-02-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tank',
            old_name='contruction_material',
            new_name='construction_material',
        ),
    ]
