# Generated by Django 4.2.7 on 2024-02-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='tank_name',
            field=models.CharField(default='Unnamed', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tank',
            name='scheme_name',
            field=models.CharField(max_length=64),
        ),
    ]
