# Generated by Django 4.2.7 on 2024-02-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_tank_has_ball_valve_tank_has_overflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='has_bulkmeter',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='tank',
            name='has_chamber',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='tank',
            name='has_washout',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='tank',
            name='has_ball_valve',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
