# Generated by Django 4.2.7 on 2024-02-15 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_treatmentprocess_scheme_treatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentprocess',
            name='num_units',
        ),
    ]
