# Generated by Django 4.2.7 on 2024-02-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_remove_treatmentprocess_num_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='tanks',
            field=models.ManyToManyField(blank=True, related_name='tanks', to='components.tank'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='treatment',
            field=models.ManyToManyField(blank=True, related_name='tps', to='components.treatmentprocess'),
        ),
    ]
