# Generated by Django 4.2.7 on 2024-02-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_alter_scheme_tanks_alter_scheme_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='tanks',
            field=models.ManyToManyField(blank=True, related_name='sch_tanks', to='components.tank'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='treatment',
            field=models.ManyToManyField(blank=True, related_name='sch_tps', to='components.treatmentprocess'),
        ),
    ]
