# Generated by Django 4.2.7 on 2024-02-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_alter_scheme_tanks_alter_scheme_treatment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='tanks',
            new_name='sch_tanks',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='treatment',
            new_name='sch_treatments',
        ),
    ]
