# Generated by Django 4.2.7 on 2024-02-16 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_rename_tanks_scheme_sch_tanks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='sch_tanks',
            new_name='list_tanks',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='sch_treatments',
            new_name='list_treatments',
        ),
    ]
