# Generated by Django 4.2.7 on 2024-02-24 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Component_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128)),
                ('task_responsibility', models.CharField(choices=[('CT', 'Caretaker(s)'), ('CBO', 'Community Organization'), ('LA', 'Local Agent')], default='CT', max_length=32)),
                ('task_interval', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly'), ('QUATERLY', 'Quarterly'), ('BIANNUALLY', 'Biannually'), ('ANNUALLY', 'Annually')], default='DAILY', max_length=32)),
                ('component', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.component')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='tasks.component_type'),
        ),
    ]
