# Generated by Django 4.2.7 on 2024-03-04 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component_type',
            options={'verbose_name': 'Component Type', 'verbose_name_plural': 'Component Types'},
        ),
    ]
