# Generated by Django 4.2.7 on 2024-03-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_component_type_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='component',
            new_name='components',
        ),
    ]
